AWSTemplateFormatVersion: "2010-09-09"

Description: "Initial apigateway resource and map to lambda"

Parameters:
  MemorySize:
    Type: String
    Default: 128
  Timeout:
    Type: String
    Default: 5
  Runtime:
    Type: String
    Default: go1.x
  Prefix:
    Type: String
    Default: dev_

Resources:
  # botNotify
  botNotify:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Prefix}botNotify
      Handler: botNotify
      Role: !ImportValue LambdaRoleArn
      Code:
        S3Bucket: lambda-zip.sila
        S3Key: botNotify.zip
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout

  # bot_event
  botEvent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Prefix}bot_event
      Handler: bot_event
      Role: !ImportValue LambdaRoleArn
      Code:
        S3Bucket: lambda-zip.sila
        S3Key: bot_event.zip
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout

  # botUploadImg
  botUploadImg:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Prefix}botUploadImg
      Handler: botUploadImg
      Role: !ImportValue LambdaWithS3RoleArn
      Code:
        S3Bucket: lambda-zip.sila
        S3Key: botUploadImg.zip
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
  
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiGatewayName
      Description: "Line Bot"
      FailOnWarnings: true

  Notify:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: notify

  NotifyMsg:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref Notify
      PathPart: "{msg}"

  Upload:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !Ref Notify
      PathPart: upload
